### ISSUE TITLE
Знакомство с Typescript

### ISSUE THREAD

**Issue by TorinAsakura** [TorinAsakura/alexgrupp25.github.io#3]
### С чем связан запрос на фичу?

Ознакомиться с азами работы с языками программирования на примере TypeScript, научиться покрывать простые кейсы по автоматизации задач с помощью ЯП и выполнить задание

### Расскажите как вы это себе видите

План
 - [x] Переменные и типы данных
 - [x] Структуры данных
 - [x] Условия
 - [x] Циклы
 - [x] Функции
 - [x] Работа с ошибками
 - [x] База Advanced JS API (методы массивов)
### Задание
Необходимо реализовать простой механизм авторизации. Должны быть удовлетворены следующие требования:

 - [x] Должны присутствовать функции для регистрации:
- `login(username, password)` - вход
- `logout()` - выход
- `register(username, password)` - регистрация
- `whoami()` - получение авторизованного на данный момент пользователя (сессии)
 - [x] При регистрации должна быть проверка: логин должен быть не короче 5 символов, пароль должен быть не короче 6. Если условие не выполняется - выбрасывать ошибку
 - [x] Должна быть возможность хранить креды (`credentials`) для нескольких пользователей
 - [x] При попытке сделать логаут без активной сессии - должна выбрасываться ошибка
 - [x] При попытке сделать `whoami` без активной сессии - выбрасывать ошибку
 - [x] При удачном вызове `whoami` в консоли должен быть вывод логина пользователя, который авторизован в данный момент
 - [x] При попытке сделать регистрацию/логин в момент, когда уже есть активная сессия - выбрасывать ошибку
 - [x] Все данные должны быть типизированы: аргументы функций, используемые переменные, возвращаемые функциями значения
#### Требования к обработке ошибок:

Ошибки (и код в целом) не должны содержать символов кириллицы, при этом в некоторых ошибках должны использоваться [шаблонные строки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals). Пример:

`User with login Dassfgfd not found`

`Password for user Johnathan is incorrect`

### Требования к оформлению задания
Задание должно быть выполнено в отдельной ветке. К этой ветке должен быть создан pull request. Если pull request еще не готов к мержу в мастер - он должен быть помечен как draft. Код должен удовлетворять проверкам lint и typecheck (`yarn lint`, `yarn typecheck`)

**Comment by alexgrupp25** [comment]
{
    "compilerOptions": {
    "target": "es2015",
    "outDir": "JS",
    "module": "ES2015",
    },
    "include": [
        "auth/auth.ts"
    ]
}
Нужна помощь. прописал эти инструкции в файле tsconfig.json, но они не прменились(сам файл ошибок не показывает) и в итоге компилируется по другим правилам

**Comment by TorinAsakura** [comment]
> {
> "compilerOptions": {
> "target": "es2015",
> "outDir": "JS",
> "module": "ES2015",
> },
> "include": [
> "auth/auth.ts"
> ]
> }
> Нужна помощь. прописал эти инструкции в файле tsconfig.json, но они не прменились(сам файл ошибок не показывает) и в итоге компилируется по другим правилам

посмотри как сделано у других
зачем тебе в 2023 году правила 2015 года?

**Comment by alexgrupp25** [comment]
Нид хелп. При выполнении команд yarn install пропадают файлы .pnp.cjs и .loader.pnp.cjs Где я потерял зависимость из-за которой они не подтягиваются?

**Comment by TorinAsakura** [comment]
@alexgrupp25 Сноси yarn, nodejs, чисти все кеши, ребутайся, сгоняй за иконой Парижской Богоматери, позвони в РПЦ отцу Кириллу и попробуй переустановить ноду и ярн…если не поможет ты должен знать "кому позвонить"

**Comment by alexgrupp25** [comment]
@TorinAsakura вот блин... номер отца Кирилла, тоже не подятнулся( пошел реинсталить
